# Generated by Django 4.2.20 on 2025-03-18 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("communityapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_stories", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="viewers",
            field=models.ManyToManyField(
                blank=True, related_name="viewed_stories", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
