# Generated by Django 4.2.20 on 2025-03-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communityapi", "0002_story_likes_story_viewers"),
    ]

    operations = [
        migrations.AddField(
            model_name="livestream",
            name="thumbnail",
            field=models.FileField(
                blank=True, null=True, upload_to="media/livestream_thumbnails/"
            ),
        ),
        migrations.AlterField(
            model_name="livestream",
            name="recording",
            field=models.FileField(
                blank=True, null=True, upload_to="media/livestream_recordings/"
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="media",
            field=models.FileField(
                help_text="Image or video file", upload_to="media/stories/"
            ),
        ),
    ]
