# Generated by Django 4.2.20 on 2025-03-22 06:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("communityapi", "0004_alter_livestream_stream_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="livestream",
            old_name="stream_url",
            new_name="stream_id",
        ),
    ]
