# Generated by Django 5.1.7 on 2025-03-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.CharField(default="", max_length=255),
        ),
    ]
