# Generated by Django 5.1.7 on 2025-03-11 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_product_subcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="subcategory",
        ),
    ]
