# Generated by Django 5.1.7 on 2025-03-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_product_subcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.ImageField(upload_to="media/products/"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="media/products/"),
        ),
    ]
