# Generated by Django 5.1.7 on 2025-03-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_usercoupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercoupon",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
    ]
