# Generated by Django 5.1.7 on 2025-03-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_reviewimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="helpful_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
