# Generated by Django 5.1.7 on 2025-03-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_review_helpful_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand_name",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
