# Generated by Django 4.2.20 on 2025-05-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_orders_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaypalOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=64, unique=True)),
                ("purchase_units", models.JSONField()),
                ("intent", models.CharField(default="CAPTURE", max_length=16)),
                ("experience_context", models.JSONField(blank=True, null=True)),
                ("status", models.CharField(max_length=32)),
                ("raw_response", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "paypal_order",
            },
        ),
    ]
