# Generated by Django 5.1.7 on 2025-03-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrepareOrder",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("receipt", models.CharField(blank=True, max_length=255, null=True)),
                ("partial_payment", models.BooleanField(default=False)),
                ("notes", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "prepare_order",
            },
        ),
    ]
