# Generated by Django 4.2.20 on 2025-05-11 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_orders_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description_file",
            field=models.FileField(
                blank=True,
                help_text="Upload a PDF to use as the description if `description` is empty.",
                null=True,
                upload_to="media/products/descriptions/",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="how_to_use",
            field=models.TextField(
                blank=True, help_text="Instructions on how to use this product."
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="ingredients",
            field=models.TextField(
                blank=True,
                help_text="List of ingredients, one per line or however you prefer.",
            ),
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                ("sold_count", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="api.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_variant",
                "ordering": ["product", "name"],
                "unique_together": {("product", "name")},
            },
        ),
    ]
