# Generated by Django 4.2.20 on 2025-05-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_orderitem_variant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="main_image",
            field=models.ImageField(blank=True, null=True, upload_to="brands/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.ImageField(upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="reviewimage",
            name="image",
            field=models.ImageField(upload_to="reviews/"),
        ),
    ]
