# Generated by Django 4.2.20 on 2025-03-30 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultantapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="contactmessage",
            table="contact_message",
        ),
    ]
