# Generated by Django 4.2.20 on 2025-04-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultantapi", "0002_alter_contactmessage_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "course_contact",
            },
        ),
    ]
