# Generated by Django 4.2.20 on 2025-04-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultantapi", "0004_course_courseuser_enrollment_coursevideo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.CharField(default="beginner", max_length=255),
        ),
        migrations.AddField(
            model_name="course",
            name="publisher",
            field=models.CharField(default="ezzikroean", max_length=255),
        ),
    ]
