# Generated by Django 4.2.20 on 2025-04-05 07:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultantapi", "0005_course_level_course_publisher"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="enrollment",
            table="course_enrollment",
        ),
    ]
