# Generated by Django 4.2.20 on 2025-04-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultantapi", "0006_alter_enrollment_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_type",
            field=models.CharField(default="free", max_length=255),
        ),
    ]
