# Generated by Django 4.2.20 on 2025-04-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultantapi", "0007_course_course_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[("free", "Free"), ("paid", "Paid"), ("drama", "Drama")],
                default="free",
                max_length=255,
            ),
        ),
    ]
