# Generated by Django 4.2.20 on 2025-04-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultantapi", "0008_alter_course_course_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visa_type",
                    models.CharField(
                        choices=[
                            ("D2", "D-2 Student"),
                            ("D4", "D-4 Language Training"),
                            ("E6", "E-6 Entertainment"),
                            ("C4", "C-4 Short-Term Work"),
                        ],
                        help_text="Which visa the user is applying for",
                        max_length=2,
                    ),
                ),
                (
                    "package_id",
                    models.CharField(
                        help_text="Identifier for the package (e.g. basic, standard, ...)",
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Full Name")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                ("phone", models.CharField(max_length=32, verbose_name="Phone Number")),
                ("arrival_date", models.DateField(verbose_name="Planned Arrival Date")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="Set to true once the booking is processed/confirmed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visa Package Booking",
                "verbose_name_plural": "Visa Package Bookings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VisaPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visa_type",
                    models.CharField(
                        choices=[
                            ("D2", "D-2 Student"),
                            ("D4", "D-4 Language Training"),
                            ("E6", "E-6 Entertainment"),
                            ("C4", "C-4 Short-Term Work"),
                        ],
                        max_length=2,
                    ),
                ),
                ("package_id", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=64)),
                (
                    "price",
                    models.PositiveIntegerField(
                        help_text="Price in USD cents or your currency"
                    ),
                ),
                ("service_include", models.TextField(blank=True, default="")),
            ],
        ),
    ]
