# Generated by Django 4.2.20 on 2025-04-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultantapi", "0011_alter_bookpackage_visa_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookpackage",
            name="visa_type",
            field=models.CharField(
                choices=[
                    ("D2", "D-2 Student"),
                    ("D4", "D-4 Language Training"),
                    ("E6", "E-6 Entertainment"),
                    ("C4", "C-4 Short-Term Work"),
                ],
                help_text="Which visa the user is applying for",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="visapackage",
            name="visa_type",
            field=models.CharField(
                choices=[
                    ("D2", "D-2 Student"),
                    ("D4", "D-4 Language Training"),
                    ("E6", "E-6 Entertainment"),
                    ("C4", "C-4 Short-Term Work"),
                ],
                max_length=4,
            ),
        ),
    ]
