# Generated by Django 4.2.20 on 2025-04-24 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("consultantapi", "0012_alter_bookpackage_visa_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisaService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visa_type",
                    models.CharField(
                        choices=[
                            ("D2", "D-2 Student"),
                            ("D4", "D-4 Language Training"),
                            ("E6", "E-6 Entertainment"),
                            ("C4", "C-4 Short-Term Work"),
                        ],
                        help_text="Which visa this service represents",
                        max_length=4,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="visa_services/"
                    ),
                ),
            ],
            options={
                "db_table": "visa_service",
                "ordering": ["visa_type"],
            },
        ),
        migrations.AddField(
            model_name="visapackage",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packages",
                to="consultantapi.visaservice",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="visapackage",
            unique_together={("service", "package_id")},
        ),
        migrations.RemoveField(
            model_name="visapackage",
            name="visa_type",
        ),
    ]
