# Generated by Django 4.2.20 on 2025-04-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultantapi", "0013_visaservice_visapackage_service_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visaservice",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/visa_services/"
            ),
        ),
    ]
