# Generated by Django 4.2.20 on 2025-04-24 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("consultantapi", "0014_alter_visaservice_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookpackage",
            name="package_id",
        ),
        migrations.RemoveField(
            model_name="bookpackage",
            name="visa_type",
        ),
        migrations.AddField(
            model_name="bookpackage",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="consultantapi.visapackage",
            ),
        ),
        migrations.AddField(
            model_name="bookpackage",
            name="service",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="consultantapi.visaservice",
            ),
            preserve_default=False,
        ),
    ]
