# Generated by Django 4.2.20 on 2025-05-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultantapi", "0015_remove_bookpackage_package_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visaservice",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="visa_services/"),
        ),
    ]
